//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemServico
    {
        public int Id { get; set; }
        public decimal Quant { get; set; }
        public string UM { get; set; }
        public string Descricao { get; set; }
        public decimal Unit { get; set; }
        public decimal Total { get; set; }
        public int ServicoId { get; set; }
    
        public virtual Servico Servico { get; set; }
    }
}
