//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visita
    {
        public int Id { get; set; }
        public int ClienteId { get; set; }
        public System.DateTime DataVisita { get; set; }
        public string Motivo { get; set; }
        public bool Realizado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
